theme:
  switch: true
  default: style-light #style-light：亮色模式 ; style-dark：暗色模式 ; auto：跟随系统选择

favicon:
  logo: log.svg
  icon16: log.svg
  icon32: log.svg
  appleTouchIcon: log.svg
  visibilitychange: true
  hidden: failure.ico
  showText: (/≧▽≦/)咦！又好了！
  hideText: (●—●)喔哟，崩溃啦！

assets:
  internal_provider: local # local | unpkg | jsdelivr
  third_party_provider: unpkg # unpkg | jsdelivr
  icons:
    type: symbol
    css:
    js: 
    # imalun的图标库
    - //at.alicdn.com/t/c/font_3637590_i4hyyea14ur.js
    # ioeah的图标库
    - //at.alicdn.com/t/c/font_4185394_lhq7d2a47x.js

cdn:
  css:
    - //npm.elemecdn.com/lxgw-wenkai-webfont@1.7.0/style.css
  js:
    head:
    base:
    async:
    defer: /_vercel/insights/script.js

user:
  name: 云深不知雀
  first_name: 不知雀
  last_name: 云深
  email: heaol426@163.com
  domain: www.ioeah.top
  avatar: /img/heao.jpg
  describe: 网站简介。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

#  导航栏 TopBars
#  顶部导航的 logo 在 favicon 中配置，主题切换按钮在 主题模式 中配置。
#  title：标题
#  url：路径，如果设置了二级菜单后，不需要已经一级菜单触发跳转可将其设置为 '#'
#  noswup：不使用局部刷新
#  target：打开链接方式，和 a 标签属性一致
#  children：二级菜单
top_bars:
  - title: 首页
    url: /
  - title: 归档
    url: /archives/
    children:
      - title: 分类
        url: /categories/
      - title: 标签
        url: /tags/
  - title: 友链
    url: /links/

sidebar:
  social: # 社交地址
    - icon: icon-github
      url: https://github.com/Heaol426
      name: Github
    - icon: icon-gitee
      url: https://gitee.com/heao426
      name: Gitee
    - icon: icon-weibo
      url: https://weibo.com/u/5848971319
      name: Weibo
    - icon: icon-zhihu
      url: https://www.zhihu.com/people/xiao-hao-11-44-65
      name: Zhihu
  typedTextPrefix:
  typedText: ["I'm a wayfarer", "人生如逆旅，我亦是行人"]
  info: # 个人信息
    - key: 地址
      val: 火星&&木卫六
    - key: 年龄
      val: undefined

banner:
  index:
    type: video
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
    bannerTitle: 花径不曾缘客扫，<br>蓬门今始为君开。
    bannerText: Hi my new friend!
  archive:
    type: img
    bgurl: https://pic3.zhimg.com/v2-230b33bf409772ea9a62be47d25cf816_r.jpg
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: THE ARTICLE ARCHIVE

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyrightYear: 2023
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 07/26/2023 19:00:00
  custom_text:

rightside:
  aside: true
  readmode: true

icons:
  # 主题切换图标
  sun: icon-sun
  moon: icon-moon
  # 首页视频播放
  play: icon-yunhang
  # 邮箱
  email: icon-email
  # 分类进入图标
  next: icon-arrow-right
  # 文章详情 日期
  calendar: icon-rili
  # 文章详情 时间
  clock: icon-shijian
  # 文章详情 作者
  user: icon-yonghu
  # 返回顶部 v1.1.3+
  back_top: icon-backtop
  # 查询 v1.1.5+
  search: icon-chaxun
  # 关闭 v1.1.5+
  close: icon-guanbi
  # 打赏 v1.1.7+
  reward: icon-qiandai
  # 用户信息和文章目录切换 v1.2.10+
  user_tag: icon-yonghu1
  toc_tag: icon-liebiao
  # 右下角固定按钮 v1.2.11+
  read: icon-yuedu
  arrows: icon-arrows-h
  # 代码块
  double_arrows: icon-angle-double-down
  copy: icon-copy

toc:
  enable: true
  list_number: true
  max_depth: 3
  min_depth: 1

post_pagination:
  enable: true
  type: large # large || small

datetime_foramt:
  post_card:
    date: YY/MM/DD
    time: HH:mm
  post_info:
    date: YY/MM/DD
    time: HH:mm
  archive:
    date: YY/MM/DD
    time: HH:mm

search:
  enable: true
  type: local
  preload: true
  trigger: auto

baidu_push: true

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

swup: true

highlight:
  title: mac
  height_limit: 200

categorie_card:
  enable: true
  len: 3
  list: ["备忘录", "记录类"]

layout:
  # 固定按钮模板
  fixed_btn: async/fixed-btn
  # 顶部菜单-查询部分
  header_search: async/empty
  # 顶部菜单-主题切换部分
  header_theme: async/empty

# 文章过期提醒
notice_outdate:
  enable: true
  style: flat
  limit_day: 90
  position: top
