theme:
  switch: true
  default: style-light #style-light：亮色模式 ; style-dark：暗色模式 ; auto：跟随系统选择

favicon:
  logo: log.svg
  icon16: log.svg
  icon32: log.svg
  appleTouchIcon: log.svg
  visibilitychange: true
  hidden: failure.ico
  showText: (/≧▽≦/)咦！又好了！
  hideText: (●—●)喔哟，崩溃啦！

assets:
  internal_provider: unpkg # local | unpkg | jsdelivr
  third_party_provider: unpkg # unpkg | jsdelivr


cdn:
  css:
  js:
    head:
    base:
    async:
    defer:

user:
  name: 云深不知雀
  first_name: 不知雀
  last_name: 云深
  email: heaol426@163.com
  domain: 
  avatar: /img/avatar.jpg
  describe: 网站简介。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

#  导航栏 TopBars
#  顶部导航的 logo 在 favicon 中配置，主题切换按钮在 主题模式 中配置。
#  title：标题
#  url：路径，如果设置了二级菜单后，不需要已经一级菜单触发跳转可将其设置为 '#'
#  noswup：不使用局部刷新
#  target：打开链接方式，和 a 标签属性一致
#  children：二级菜单
top_bars:
  - title: 首页
    url: /
  - title: 归档
    url: /archives/
  - title: 分类
    url: /categories/

sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/Heaol426
  typedTextPrefix: I`m
  typedText: [" a wayfarer"]
  info: # 个人信息
      - key: 地址
        val: 火星&&木卫六
      - key: 年龄
        val: undefined    

banner:
    index:
        type: video
        bgurl:  //cdn.moji.com/websrc/video/autumn20190924.mp4
        bannerTitle: 树深时见鹿，<br>溪午不闻钟。
        bannerText: Hi my new friend!

footer:
  powered:
    enable: true
  beian:
    enable: true
    icp: 
  copyrightYear:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 07/26/2023 19:00:00
  custom_text:

rightside:
    aside: true
    readmode: true

icons:
    # 主题切换图标
    sun: far fa-sun
    moon: far fa-moon
    # 首页视频播放
    play: fas fa-play
    # 邮箱
    email: far fa-envelope
    # 分类进入图标
    next: fas fa-arrow-right
    # 文章详情 日期
    calendar: far fa-calendar-alt
    # 文章详情 时间
    clock: far fa-clock
    # 文章详情 作者
    user: far fa-user
    # 返回顶部 v1.1.3+
    back_top: fas fa-arrow-up
    # 查询 v1.1.5+
    search: fas fa-search
    # 关闭 v1.1.5+
    close: fas fa-times
    # 打赏 v1.1.7+
    reward: fas fa-hand-holding-usd
    # 用户信息和文章目录切换 v1.2.10+
    user_tag: fas fa-user-alt
    toc_tag: fas fa-th-list
    # 右下角固定按钮 v1.2.11+
    read: fas fa-book-reader
    arrows: fas fa-arrows-alt-h
    # 代码高亮折叠 v2.0.0+
    double_arrows: fas fa-angle-double-down
    # 代码复制
    copy: fas fa-copy

